// Фоновая сцена главного экрана: ночная лавка алхимика (стена, пол, окно, полки).
// Намеренно тёмная и малоконтрастная, чтобы котёл, числа и UI читались поверх неё.
// bg_wall — бесшовный тайл по X и Y; bg_floor — бесшовный по X (ряды 5..15 повторяются и по Y).
// Сгенерировано скриптом-помощником; правится вручную как обычные строки.
import type { SpriteSet } from './sprite';

/** Тёплое тёмное дерево из UI-токенов + приглушённые акценты. Перекрывает часть ключей общей палитры. */
const SCENE_PAL: Record<string, string> = { a: '#120e0b', b: '#15110e', c: '#1c1612', d: '#211a15', e: '#241d17', f: '#2b231c', g: '#3d322a', h: '#4a3c30', v: '#15122a', V: '#1a1631', w: '#211b39', M: '#a9a286', Q: '#7d7662', T: '#2c5d58', i: '#1a3a38', I: '#4f8a80', A: '#80561f', j: '#4f3515', J: '#b0823f', O: '#6e3544', q: '#43212b', W: '#9c5a6c', Z: '#4b3a6c', l: '#2e2445', L: '#76629a', K: '#4d3727', R: '#51272a', G: '#28402f', B: '#28304a', H: '#6b604c', U: '#7c735c', u: '#524b3c', y: '#f2b84b', Y: '#fee761', o: '#b8612a', D: '#223826', P: '#3f5c33', S: '#2b3634', s: '#4e5f5b' };

export const SCENE_ART: SpriteSet = {
  bg_wall: { w: 32, h: 32, pal: SCENE_PAL, px: [
    'aedddddcafeeeeccaeddcfdcafeececc',
    'aedddddcafeececcaecdcfdcafeeeecc',
    'aedfdddcafecccccaecddfdcafeeeecc',
    'aedfdddcafecbbccaecddfdcafeeeecc',
    'aedfdddcafecccccaecdcfdcaaaaaaaa',
    'aedfdddcaffcecccaecdcfdcaffffffc',
    'aedfdddcaffeeeccaecdcfdcafefeecc',
    'aedfdddcaffeeeecaecdcfdcafefeecc',
    'aedfdddcaffeceecaeddcfdcafefeecc',
    'aedhdcdcaffeceecaeddcddcafefeecc',
    'aedfacdcaffeceecaedccddcafefeecc',
    'aaaaaaaaaffeceecaedccddcafefeeec',
    'aeeeeeecaffeceecaedccddcafefeeec',
    'aefcdhdcaffeceecaedccddcafefeeec',
    'aefcfcacaffeceecaedcdddcafefecec',
    'aefcfcdcaffeceecaedcdddcafefecec',
    'aefcfcdcafeeceecaedcdddcafefecec',
    'aefcfcdcafeeceecaedhdddcafeeecfc',
    'aefcfcdcafeeceecaedcaddcafeeecfc',
    'aefcfcdcafeeefecaaaaaaaaafeeecfc',
    'aefcfcdcafeeefecaeeeeeecafeeecfc',
    'aefcfcdcafeeefecaedddhfcafeeecfc',
    'aecdfcdcafeeefecaeddddacafeeeefc',
    'aeddfcdcafeeefecaeddddfcafceeeec',
    'aeddfcccafeeefecaeddddfcafceeeec',
    'aeddfdccafeeeeecaeddddfcafceeeec',
    'aeddddccafeeeeecaedddddcafcceeec',
    'aeddddccaaaaaaaaaedddddcafccccec',
    'aeddddccaffffffcaeddcddcafccccec',
    'aeddddccafeeeeccaeddcfdcafccccec',
    'aeddddccafeeeeccaeddcfdcafceccec',
    'aeddddccafeeeeccaeddcfdcafceceec',
  ] },
  bg_floor: { w: 32, h: 16, pal: SCENE_PAL, px: [
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
    'gggggggggggggggggggggggggggggggg',
    'gggfggggggggggfggggggggggfgggggg',
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'cccccccccccccccccccccccccccccccc',
    'gggggggchggggggggggggggchggggggg',
    'eeeffeecgffffffffffffffcgfeeeeee',
    'cccccccccccccccccccccccccccccccc',
    'gggggggggggggggchgggggggggggggch',
    'ffffffffffffffecgeeeeeeeeeeeefcg',
    'fffffffffeeeeeecgeeeffffffffffcg',
    'cccccccccccccccccccccccccccccccc',
    'ggchgggggggggggggggchggggggggggg',
    'ffcgeeeeeeeeeeeefffcgfffffffffff',
    'ffcgffffffffeeeeeeecgeeeefffffff',
  ] },
  bg_window: { w: 40, h: 48, pal: SCENE_PAL, px: [
    '........................................',
    '.................aaaaaa.................',
    '..............aaagggfffaaa..............',
    '...........aaaggggggffffffaaa...........',
    '..........agggggccccccccfffffa..........',
    '........aagggcccv3vgevvvcccfffaa........',
    '.......aggggcvvvvvvgevvvvvvcffffa.......',
    '......agggccvvvvvvvgevvvvvvvccfffa......',
    '......aggcvvvvvvvvvgevvvvv4vvvcffa......',
    '.....aggcvQMvvvvvvvgevvvvvvvvvvcffa.....',
    '....agggcvMMvvvvvvvgevvvvvvvvvvcfffa....',
    '....aggcvQMMvvvvvvvgevvvvvvvv3vvcffa....',
    '...aggcvvvMMMvvvvvvgevvvvvvv343vvcffa...',
    '...aggcvvvQMMMQvvvvgevvvvvvvv3vvvcffa...',
    '...agcvvvvvvQvvvvvvgevvvvvvvvvvvvvcfa...',
    '..aggcvVvVvVvVvVvVvgeVvVvVvVvVvVvVcffa..',
    '..aggcvVvVvVvVvVvVvgeVvVvVvVvVvVvVcffa..',
    '..aggcVVVVVVVVVVVVVgeVVVVVVVVVV3VVcffa..',
    '..agcVVVVVVVVVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcVVVVVVVVVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcVVVVVVVVVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcVVV3VVVVVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcVVVVVVVVVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcVVVVVVVVVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcVVVVVV3VVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcgggggggggggggggeggggggggggggggcfa..',
    '..agceeeeeeeeeeeeeegeeeeeeeeeeeeeeecfa..',
    '..agcVVVVVVVVVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcVVVVVVVVVVVVVVgeVVVVVVVVVVVVVVcfa..',
    '..agcwVwVwVwVbbwVwVgewVwVwVwVwVwVwVcfa..',
    '..agcwVwVwVwVbbwVwVgewVwVwVwVwVwVwVcfa..',
    '..agcwwwwwwwwbbwwwwgewwwwwwwwwwwwwwcfa..',
    '..agcwwwwwwwwbbwwbbgewwwwwwwwwwwwwwcfa..',
    '..agcwwwwwwwwwwbbbbgewwwwwwwwwwwwwwcfa..',
    '..agcwwwbbwwwwwbbbbgewwwwwwwbbwwwwwcfa..',
    '..agcwwbbbbwwwwbbbbgebbwwwbbbbbbwwwcfa..',
    '..agcbbbbbbbbwwbbbbgebbbbbbbbbbbbwwcfa..',
    '..agcbbbbbbbbbbbbbbgebbbbbbbbbbbbbbcfa..',
    '..agcbbbbbbbbbbbbbbgebbbjbbbbbbbbbbcfa..',
    '..agcbbbbbbbbbbbbbbgebbbbbbbbbbbbbbcfa..',
    '..agcbbbbbbbbbbbbbbgebbbbbbbbbbbbbbcfa..',
    '..agccccccccccccccccccccccccccccccccfa..',
    '..ffffffffffffffffffffffffffffffffffff..',
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
    'gggggggggggggggggggggggggggggggggggggggg',
    'ffffffffffffffffffffffffffffffffffffffff',
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  ] },
  bg_shelf: { w: 72, h: 28, pal: SCENE_PAL, px: [
    '........................................................................',
    '........................................................................',
    '........................................................................',
    '........................................................................',
    '........................................................................',
    '........................................................................',
    '..........................KKk...........................................',
    '..........................afa....................................o......',
    '..........................afa.................KKk................y......',
    '...................KKk....afa.................afa................y......',
    '...................afa....afa....KKk..........afa...............oYo.....',
    '...................afa...agffa...afa..........afa................a......',
    '...................afa...aJJja...afa..........afa...............uUu.....',
    '.aaaaaaaaaaa......agffa..aJAja...afa...KKk...agffa.....KKk......UUu.....',
    '.aBBBBBBBBBHa....agffffa.aJAja.agffffa.afa...agffa.....afa.....UUUu.....',
    '..aaaaaaaaaaaa..aIIIIIIiaaJAja.aWWWWqa.afa..aLLLLla....afa.....uUUu.....',
    '..aGhGGGGGhGGHa.aITTTTTiaaJAja.aWOOOqaagffa.aLZZZla...agffa.....UUu.....',
    '..aGGGGGGGGGGHa.aITTTTTiaaJAja.aWOOOqaaJJjaaLZZZZZla.aWWWWqa....UUu...f.',
    '.aaaaaaaaaaaaaa.aITTTTTiaaJAja.aWOOOqaaJAjaaLZZZZZla.aWOOOqa....UUu..gf.',
    '.aRhRRRRRRRhRRHa.aITTTia.aJAja.aWOOOqaaJAjaLZZZZZZZlaaWOOOqa.fgggggggf..',
    '.aRRRRRRRRRRRRHa..aaaaa..aaaaa.aaaaaaaaaaaaaaaaaaaaaa.aaaaa...fffffff...',
    'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
    'gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
    'effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
    '.bbbbbghfcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbghfcbbbbb.',
    '......gfc.....................................................gfc.......',
    '......gc......................................................gc........',
    '......g.......................................................g.........',
  ] },
  bg_shelf2: { w: 56, h: 24, pal: SCENE_PAL, px: [
    '........................................................',
    '........................................................',
    '........................................................',
    '........................................................',
    '........................................................',
    '..KKKKKKKk....DP.P.D....................................',
    'KKKKKKKKKKKk...D.DP.D...................................',
    '.aaaaaaaaaa.....P.P.....................................',
    '.asSSSSSSSa.....PD.....................Z................',
    '.asSSSSSSSa...gggggg...................Z.....aaaaaaaa...',
    '.asSSSSSSSa...asSSSa....aaaaa.........LZl...aUUUURUUUu..',
    '.asDPDDPDDa...asSSSa...aUUUUUa.......LLZll..aUUUURUUUka.',
    '.asPDDPDDPa...asSSSa..aUUUUUUua.....ZLLZll..auuuuRuuuu..',
    '.asDDPDDPDa...asSSSa..aUaaUaaua.....ZLLZllZ..aaaaaaaaa..',
    '.asDPDDPDDa...ajjjja..aUaaUaaua....LZLLZllZ..aUUURUUUUu.',
    '.asPDDPDDPa...ajjjja...aUUaUua.....LZLLZlLZl.aUUURUUUUka',
    '.asDDPDDPDa...ajjjja....aUuUa......LZLLZlLZl.auuuRuuuuu.',
    '.aaaaaaaaaa...aaaaaa....auaua......LZLLZlLZl..aaaaaaaa..',
    'ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
    'gggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
    'effffffffffffffffffffffffffffffffffffffffffffffffffffffe',
    '.bbbbghcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbghcbbbb.',
    '.....gc.........................................gc......',
    '.....g..........................................g.......',
  ] },
};
